language: node_js
node_js: "6.10.0"
script:
  - echo "Scripting"  
  - npm start
install:
  - echo "installing"
  - npm install -g firebase-tools
  - ./functions/npm install
  - npm install
after_success:
  - echo "Success"
  # - echo $TRAVIS_TEST_RESULT
  - firebase deploy --token $FIREBASE_TOKEN
after_failure:
  - echo "Failure"
after_script: 
  - echo "after script"